config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :new, :create, :edit, :update]
  root 'users#index'
  resources :users, only: [:index, :new, :create, :edit, :update] do
  collection do
    get 'search'
  end
end
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :message
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :message
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :group
  belongs_to :user,optional: true
  
  validates :text, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :likes
  has_many :comments
  has_many :group_users
  has_many :groups, through: :group_users
  has_one_attached :image
  validates :name, presence: true
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    respond_to do |format| 
      format.html
      format.json { @new_messages = Message.where('id > ?', params[:message_id]) } 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group)
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    # インスタンス変数を定義したら、doneに送られる。
      @message = @group.messages.new(message_params)
      Message.create(image: message_params[:image], user_id: current_user.id)
      if @message.save
        respond_to do |format|
          format.html{ redirect_to group_messages_path(params[:group_id]) }
          format.json
        end
      else
        flash.now[:alert] = 'メッセージを入力してください。'
        render :index
      end
    end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery 

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_parems)
  if @user.save
    redirect_to root_path
  else
    render new
  end
end


  def edit
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  def search
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: params[:user_id])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for:"chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_グループメンバー"} グループメンバー
    .chat-group-form__field--right
      .chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input#group_user_ids.member_list{:name => "group[user_ids][]", :type => "hidden", :value => current_user.id}/
          %p.chat-group-user__name
            = current_user.name
        - @group.users.each do |user|
          - if user != current_user
            .chat-group-user.clearfix.js-chat-member
              %input#group_user_ids.member_list{:name => "group[user_ids][]", :type => "hidden", :value => user.id}/
              %p.chat-group-user__name
                = user.name
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 グループ編集
  = render partial: 'form', locals: { group: @group }
  -# %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", action: "/chat_groups/22", method: "post"}
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{name: "chat_group[name]", placeholder: "グループ名を入力してください", type: "text", value: "ほげー"}/
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/groups/index.html.haml
- if user_signed_in?
  = render 'messages/main'
- else
  .top-page
    %h1 Original story
    .top-page__text
      / ユーザーがログインしていなかった時の処理
      = link_to " Log_in", new_user_session_path, class: 'post'
      / ログイン画面に移行する
      = link_to "Sign_up", new_user_registration_path, class: 'post'
      / 新規登録画面に移行する

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規グループ
  = render 'form', { group: @group }
  = form_for @group do |f|
    -# - if @group.errors.any?
    -#   .chat-group-form__errors
    -#     %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
    -#     %ul
    -#       - @group.errors.full_messages.each do |message|
    -#         %li= message
    -# .chat-group-form__field
    -#   .chat-group-form__field--left
    -#     = f.label :name, class: 'chat-group-form__label'
    -#   .chat-group-form__field--right
    -#     = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    -# .chat-group-form__field.clearfix
    -#   / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    -#   /
    -#     <div class='chat-group-form__field--left'>
    -#     <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
    -#     </div>
    -#     <div class='chat-group-form__field--right'>
    -#     <div class='chat-group-form__search clearfix'>
    -#     <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
    -#     </div>
    -#     <div id='user-search-result'></div>
    -#     </div>
    -# .chat-group-form__field.clearfix
    -#   .chat-group-form__field--left
    -#     %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    -#   .chat-group-form__field--right
    -#     / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
    -#     = f.collection_check_boxes :user_ids, User.all, :id, :name
    -#     / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    -#     /
    -#       <div id='chat-group-users'>
    -#       <div class='chat-group-user clearfix' id='chat-group-user-22'>
    -#       <input name='chat_group[user_ids][]' type='hidden' value='22'>
    -#       <p class='chat-group-user__name'>seo_kyohei</p>
    -#       </div>
    -#       </div>
    -# .chat-group-form__field.clearfix
    -#   .chat-group-form__field--left
    -#   .chat-group-form__field--right
    -#     = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title StoryOfMyLife
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_footer.html.haml
.form
  = form_with model: [@group,@message], id: "new_message",local: true do |f|
    = f.text_field :text, class: 'form__message', placeholder: 'メッセージを入力してください'
    .form__mask
      = f.label :image, class: 'form__mask__image' do
        = f.file_field :image, class: 'hidden'
    = f.submit '送信', class: 'form__submit'

app/views/messages/_header.html.haml
.message-header
  .header-text
    .header-text__group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group),class:"link_group" do
          .header-text__group__box
            .header-text__group__box__name
              Group name
            .header-text__group__box__nm
              = group.name

app/views/messages/_main.html.haml
- if user_signed_in?
  / ユーザーがログインしているか調べる
  / ユーザーがログインしていた時の処理
  = render 'messages/header'
  = render 'messages/side'
  .message-main
  .message-main__header
- else
  .top-page
    %h1 Original story
    .top-page__text
      / ユーザーがログインしていなかった時の処理
      = link_to " Log_in", new_user_session_path, class: 'post'
      / ログイン画面に移行する
      = link_to "Sign_up", new_user_registration_path, class: 'post'
      / 新規登録画面に移行する

app/views/messages/_message.html.haml
.message(data-message-id='#{message.id}')
  .message-user
    = message.user.name
  .message-font
    .message-font__content
      - if message.text.present?
        = message.text
    .message-font__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
= image_tag message.image.url if message.image.present?

app/views/messages/_side.html.haml
- if @group
  .message-side
    .side-text
      .side-text__name
        %h2 My name
        =current_user.name 
      .side-text__user
        = link_to "Edit user", edit_user_path(current_user)
      .side-text__new
        = link_to "New group",  new_group_path
      .side-text__edit
        = link_to "Edit group", edit_group_path(@group)
      .side-text__out
        = link_to "Log out", destroy_user_session_path, method: :delete
- else
  .message-side
    .side-text
      .side-text__name
        %h2 My name
        =current_user.name 
      .side-text__user
        = link_to "Edit user", edit_user_path(current_user)
      .side-text__new
        = link_to "New group",  new_group_path
      .side-text__out
        = link_to "Log out", destroy_user_session_path, method: :delete

app/views/messages/index.html.haml
- if user_signed_in?
  = render 'messages/header'
  .message-main
    = render 'messages/side'
    .messages
      = render @messages
  = render 'messages/footer'
- else
  .top-page
    %h1 Original story
    .top-page__text
      / ユーザーがログインしていなかった時の処理
      = link_to " Log_in", new_user_session_path, class: 'post'
      / ログイン画面に移行する
      = link_to "Sign_up", new_user_registration_path, class: 'post'
      / 新規登録画面に移行する

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'